# https://github.com/embarkmobile/android-maven-example
language: cpp
compiler:
    - clang
    - gcc
install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libboost-all-dev
script:
    - make test
